### ISSUE TITLE
Prevents updates from being installed on Mojave

### ISSUE THREAD

**Issue by Coteh** [emreyolcu/discrete-scroll#10] opened 2019-09-05 15:51 UTC
This issue occasionally comes up when trying to install updates on Mojave. I end up having to install the update manually to work around it.

<img width="683" alt="Screen Shot 2019-09-05 at 11 33 48 AM" src="https://user-images.githubusercontent.com/3276350/64357798-573a5300-cfd3-11e9-9d1b-10755d388c50.png">

**Comment by emreyolcu** [comment] 2020-04-08 17:19
Does this keep happening on Catalina? If not, I will close the issue since there are no other reports and I could not reproduce it.

**Comment by Coteh** [comment] 2020-04-08 18:26
I do not have Catalina currently. When I get it and this happens again, I’ll open up another issue.

On Apr 8, 2020, at 1:19 PM, Emre Yolcu <notifications@github.com<mailto:notifications@github.com>> wrote:


Does this keep happening on Catalina? If not, I will close the issue since there are no other reports and I could not reproduce it.

**Comment by emreyolcu** [comment] 2020-04-08 18:27
Thank you.

**Closed as completed by emreyolcu** 2020-04-08 18:27 UTC
